### ISSUE TITLE
Rodando no Linux

### ISSUE THREAD

**Issue by Filipizaum** [pythonprobr/pythonbirds#4]
Tentei rodar o arquivo no GNU/Linux Mint 16, mas não apareceu nada além de gráficos no terminal.
Era pra ser assim mesmo? ou era pra aparecer os gráficos normais?

**Comment by giovaneliberato** [comment]
@Filipizaum esquecemos de especificar no tutorial de como rodar, mas no linux é preciso instalar o pacote tkinter

para rodar o jogo no modo gráfico é só executar python placa_grafica_tkinter.py

**Comment by renzon** [comment]
Na realidade eu comentei isso na lista da python brasil. De toda forma, se
rodou a versão no console, vc deve ter visto apenas o primeiro vídeo. Veja
esse aki:

https://www.youtube.com/watch?v=JRzhPjwseC0&list=PLA05yVJtRWYTm0sIa6n56UpCjCsR5ekla&index=4

Ainda falta fazer a atualização da documentação.

 Abs,

## 

  Renzo Nuccitelli
  www.python.pro.br

2014-07-21 16:35 GMT-03:00 Giovane Liberato notifications@github.com:

**Comment by Filipizaum** [comment]
Desculpa pessoal, eu sou muito apressado. Depois que fiu ver como roda a versão placa_grafica_tkinter.py.

Obrigado
